### ISSUE TITLE
variable referenced before assignment

### ISSUE THREAD

**Issue by Dauth** [garrettfoster13/aced#1]
`[proxychains] Strict chain  ...  127.0.0.1:9052  ...  10.9.15.10:389  ...  OK                                                                                                                                    
Enter target sAMAccountName or distinguishedName: administrator                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                               
  File "/home/test/Desktop/aced/aced.py", line 4, in <module>                                                                                                                                          
    lib.main()                                                                                                                                                                                                   
  File "/home/test/Desktop/aced/lib/main.py", line 791, in main                                                                                                                                        
    ldapsearch=magic(ldap_server, ldap_session, domain, logs_dir)                                                                                                                                                
  File "/home/test/Desktop/aced/lib/main.py", line 390, in __init__                                                                                                                                    
    self.WRITE_SPN = self.resolve_key("(cn=Service-Principal-Name)")                                                                                                                                             
  File "/home/test/Desktop/aced/lib/main.py", line 494, in resolve_key                                                                                                                                 
    return guid                                                                                                                                                                                                  
UnboundLocalError: local variable 'guid' referenced before assignment`

This occurs when it is not able to determine both the 1) domain and 2) user. By initializing the guid variable in the beginning of the function, it would return a none value for both domain and user.

**Comment by garrettfoster13** [comment]
Good catch! I added what you suggested and initialized the guid variable at the beginning of the function. I believe that should resolve the issue you're experiencing. I'll try and validate soon but won't have access to my lab for some time.

**Comment by garrettfoster13** [comment]
Tested changes which resolved the issue. Thanks again Dauth.
